### ISSUE TITLE
Requesting permissions on app start

### ISSUE THREAD

**Issue by andrewpmoore** [DwayneCoussement/flutter_geofence#12]
We are using this plugin, but I've noted (on android at least) that as soon as I'm using it, I get the app on first run ask for permissions straight away.

I think this is coming from 

`GeneratedPluginRegistrant.registerWith(flutterEngine);`

in the MainActivity of the app from what I can tell.
Firstly is that what you'd expect and also can you think of a way to defer this until the permission is granted in the app itself so we can let the user know why it's needed at the point it's needed?

Thanks

**Comment by DwayneCoussement** [comment]
Hi,

That's a valid concern! I did it this way for simplicity to get started, but there's plenty of cases that the user of the plugin would want to do this on another moment.

It's also not hard to move this logic.

Thanks for your feedback!

**Comment by niypoo** [comment]
> We are using this plugin, but I've noted (on android at least) that as soon as I'm using it, I get the app on first run ask for permissions straight away.
> 
> I think this is coming from
> 
> `GeneratedPluginRegistrant.registerWith(flutterEngine);`
> 
> in the MainActivity of the app from what I can tell.
> Firstly is that what you'd expect and also can you think of a way to defer this until the permission is granted in the app itself so we can let the user know why it's needed at the point it's needed?
> 
> Thanks

Yup , I have facing this , It's will be nice if we request user when init the package any place in app , 
@DwayneCoussement  thanks for your great work

**Comment by niypoo** [comment]
any new in this issue !!?
