### ISSUE TITLE
unregister all registerGeofence

### ISSUE THREAD

**Issue by niypoo** [DwayneCoussement/flutter_geofence#13]
I'm wondering is there any way to unregister all registerGeofence, in case if user register  and accidentally I miss the coordinates !

**Comment by debkanchan** [comment]
Yes there is and it is mentioned in docs

**Comment by niypoo** [comment]
I only found unregister one location by geoLocation not all locations !

**Comment by debkanchan** [comment]
then you should keep a list of all the ids and locations and loop over each and delete them

**Comment by DwayneCoussement** [comment]
See also: https://github.com/DwayneCoussement/flutter_geofence/pull/27
