### ISSUE TITLE
current location is not printed in console 

### ISSUE THREAD

**Issue by aTeamSolace** [DwayneCoussement/flutter_geofence#21]
```
          RaisedButton(child: Text("get user location"), onPressed: () {
           print("great user location");
            Geofence.getCurrentLocation().then((coordinate) {
              print("great got latitude: ${coordinate.latitude} and longitude: ${coordinate.longitude}");
            });
          })
```

by click on this i get **great user location** this in my console but the location is not printed?
is there any issue or this is not printing at each time ?

**Comment by aTeamSolace** [comment]
_Unhandled Exception: NoSuchMethodError: The getter 'first' was called on null._ this error occured here 
```
    Geofence.getCurrentLocation().then((coordinate) {
      print("great got latitude: ${coordinate.latitude} and longitude: ${coordinate.longitude}");
    });
```

**Comment by Luktm** [comment]
I also facing this issue  `Geofence.getCurrentLocation()` did not print on the console, what do you mean _Unhandled Exception: NoSuchMethodError: The getter 'first' was called on null. this error occurs here?

**Comment by Luktm** [comment]
I also facing this issue  `Geofence.getCurrentLocation()` did not print on the console. Have you found the solution from this problem?

**Comment by Luktm** [comment]
> _Unhandled Exception: NoSuchMethodError: The getter 'first' was called on null._ this error occured here
> 
> ```
>     Geofence.getCurrentLocation().then((coordinate) {
>       print("great got latitude: ${coordinate.latitude} and longitude: ${coordinate.longitude}");
>     });
> ```

Hi @aTeamSolace, I am now facing the problem, getCurrenctLocation() latitude and longitude did not print out on the console, any solution for this?

**Comment by Luktm** [comment]
there is the solution is the request permission, I have accepted the permission request, maybe there is the bug there. So I clean the app from the emulator settings then request the permission again. Wala it works.
