### ISSUE TITLE
Android manifest GeofencePlugin does not extend Service

### ISSUE THREAD

**Issue by dacianf** [DwayneCoussement/flutter_geofence#25]
When I'm trying to make a release apk the lint vital returns `GeofencePlugin must extend android.app.Service` on the following line from manifest
 ```
<service android:name="com.intivoto.geofence.GeofencePlugin"
    android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true"/>
```
I've deleted this from Manifest and the build works fine now. I think this should be removed from documentation.

**Comment by dacianf** [comment]
> When I'm trying to make a release apk the lint vital returns `GeofencePlugin must extend android.app.Service` on the following line from manifest
> 
> ```
>    android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true"/>
> ```
> 
> I've deleted this from Manifest and the build works fine now. I think this should be removed from documentation.

**Comment by exalandru** [comment]
In `FlutterGeofencePlugin.kt` I added :
```kotlin
import android.app.Service;
import android.content.Intent;
import android.os.IBinder;
```

Changed
```kotlin
class FlutterGeofencePlugin : FlutterPlugin, MethodCallHandler, ActivityAware, PluginRegistry.RequestPermissionsResultListener
// to :
class FlutterGeofencePlugin() : FlutterPlugin, MethodCallHandler, ActivityAware, PluginRegistry.RequestPermissionsResultListener, Service()
```

then also added
```kotlin
override fun onBind(p0: Intent): IBinder? {
    return null;
}
```

and it now builds with no errors !
