### ISSUE TITLE
Android location permissions asked when app is started

### ISSUE THREAD

**Issue by michelaSpreghini** [DwayneCoussement/flutter_geofence#41]
I have read in the changelogs that with flutter_geofence 0.2.0 i can ask permissions whenever it's needed.
After upgrading Flutter to flutter 2.0.5 and flutter_geofence to 0.4.1 
location permissions are always asked when the app is started insted of when i choose to ask them.
How i can fix this?

**Comment by michelaSpreghini** [comment]
I saw that the error has already been fixed with #12, but for me the issue still persists

**Comment by calmog** [comment]
+1
Permission is triggered on startup consistently, on both device and emulator.

**Comment by mvarendorff** [comment]
This seems to have been reintroduced in b738ec941aa7e19cbfc940b39253170283afd8df, removing the requestPermission calls might just be enough to fix this already?

**Comment by joshcase** [comment]
Rolling back to: `flutter_geofence: 0.3.0` resolved this for me as a workaround.

**Comment by NeatFastro** [comment]
yep, indeed a duplicate, but the solution there "to use the 0.3.0 version" is no null safe
