### ISSUE TITLE
Pub.dev readme is not updated with master branch

### ISSUE THREAD

**Issue by vinothvino42** [DwayneCoussement/flutter_geofence#49]
The last commit ([632a0f](https://github.com/DwayneCoussement/flutter_geofence/commit/632a0f7a43d44a361e25467ecc01c5da93c94bee)) in the master branch is not reflected in the pub.dev. Still, the documentation shows the package name as `com.intivoto.geofence` instead of `com.intivoto.flutter_geofence` for the **receiver** and **service** tag in the `AndroidManifest.xml`. Also the service tag should be `<service android:name="com.intivoto.geofence.FlutterGeofencePlugin" />` instead of `<service android:name="com.intivoto.geofence.GeofencePlugin" />`

**Comment by marcolettieri** [comment]
FlutterGeofencePlugin isn't even a service
