### ISSUE TITLE
app's location permission page automatically opens on app launch when "ACCESS_BACKGROUND_LOCATION" is defined in the androidManifest file

### ISSUE THREAD

**Issue by NeatFastro** [DwayneCoussement/flutter_geofence#54]
When the app get's launched then the package automatically asks for location permissions and on android 11 this results in opening the app's location permissions page instead of showing a dialog.

flutter: 2.10.2
flutter_geofence: 0.4.2

**Comment by NeatFastro** [comment]
Is anyone here?

**Comment by mvarendorff** [comment]
Duplicate of #41 ?

**Comment by NeatFastro** [comment]
looks like @mvarendorff already made a PR for this issue, and it just removes the invocation of "requestPermission" method in two places, can you (@geisterfurz007)  please review and merge it?

**Comment by mvarendorff** [comment]
I am not a maintainer on this repo so no can do, sorry!

**Comment by mvarendorff** [comment]
The PR has been closed, it seems but there hasn't been a new release yet. If you need the fix immediately, you can set the dependency like this:

```yml
  flutter_geofence:
    git:
      url: https://github.com/DwayneCoussement/flutter_geofence
      ref: main
```

**Comment by NeatFastro** [comment]
Thanks for the tip
