### ISSUE TITLE
Notification on backgroud

### ISSUE THREAD

**Issue by coppolla** [DwayneCoussement/flutter_geofence#6]
hi 
is there anyway to get notifications when state changes on the background ?

**Comment by kroobroeck** [comment]
@coppolla I just made a contribution as the example app also wasn't working for me. You can try it out and see if this fixes your problem. Basically, it had to do with the background permission.

If you use the example app with a mock app for your gps location you can try mock your gps location to the fixed coordinates `latitude: 50.853410, longitude: 3.354470` after clicking on add region in the example app. Then you should receive a notification in the background
