### ISSUE TITLE
Set Current Position from Other Plugin

### ISSUE THREAD

**Issue by CurtesMalteser** [DwayneCoussement/flutter_geofence#7]
Hi,
would be possible to implement a method from where we could pass the current position from other plugin in orther to trigger the _entryCallback and _exitCallback?
Even if that had to be converted to Coordinates()?
If makes sense.
But that would make possible to use other utils from other plugins. Happens that my map isn't rendered this way and I'm getting memory leak.

**Comment by DwayneCoussement** [comment]
this is 100% possible; with startListening those callbacks are set, and that should be your way to call into other plugins.
